/*
 * EL TORERO MENU PRICES
 *
 * Edit prices ONLY in this file.
 * Format: "Section > ITEM NAME": "9.99"
 * For duplicate items in one section, use an array in display order.
 */
window.MENU_PRICE_OVERRIDES = {
  "Appetizers > CHEESE DIP": "9.50",
  "Appetizers > GUACAMOLE DIP": "9.50",
  "Appetizers > QUESADILLA": "5.00",
  "Appetizers > SPECIAL QUESADILLA": "8.00",
  "Appetizers > STUFFED QUESADILLA": "7.50",
  "Appetizers > SPECIAL STUFFED QUESADILLA": "10.50",
  "Appetizers > QUESADILLA PLATTER": "16.75",
  "Appetizers > CHEESE NACHOS": "10.25",
  "Appetizers > HALF-ORDER CHEESE NACHOS": "7.50",
  "Appetizers > NACHOS": ["8.50", "9.25"],
  "Appetizers > HALF-ORDER NACHOS": ["6.50", "7.00"],
  "Appetizers > SPECIAL NACHOS": "11.00",
  "Appetizers > HALF-ORDER SPECIAL NACHOS": "7.75",
  "Soups & Salads > GUACAMOLE SALAD": "6.25",
  "Soups & Salads > TACO SALAD": "10.00",
  "Soups & Salads > SPECIAL TACO SALAD": "11.25",
  "Soups & Salads > TORTILLA SOUP WITH CHICKEN OR SHRIMP": "10.25",
  "Soups & Salads > POZOLE SOUP": "10.25",
  "Lunch > SPEEDY GONZALEZ": "9.10",
  "Lunch > SPECIAL LUNCH #1": "10.95",
  "Lunch > SPECIAL LUNCH #2": "9.95",
  "Lunch > SPECIAL LUNCH #3": "9.95",
  "Lunch > SPECIAL LUNCH #4": "9.10",
  "Lunch > SPECIAL LUNCH #5": "9.95",
  "Lunch > SPECIAL LUNCH #6": "9.95",
  "Lunch > SPECIAL LUNCH #7": "10.95",
  "Lunch > SPECIAL LUNCH #8": "9.95",
  "Lunch > SPECIAL LUNCH #9": "9.10",
  "Lunch > SPECIAL LUNCH #10": "9.95",
  "Lunch > SPECIAL LUNCH #11": "9.10",
  "Lunch > SPECIAL LUNCH #12": "9.95",
  "Lunch > SPECIAL LUNCH #13": "9.10",
  "Lunch > SPECIAL LUNCH #14": "9.95",
  "Lunch > SPECIAL LUNCH #15": "10.45",
  "A La Carte > ORDER OF BEANS": "3.00",
  "A La Carte > ORDER OF RICE": "3.00",
  "A La Carte > ORDER OF TACOS (3)": "10.25",
  "A La Carte > ORDER OF TAMALES (3)": "11.00",
  "A La Carte > ORDER OF ENCHILADAS (3)": "11.00",
  "A La Carte > ORDER OF BEEF TOSTADAS (2)": "11.00",
  "A La Carte > ORDER OF BURRITOS (2)": "11.00",
  "A La Carte > ORDER OF CHALUPAS (2)": "11.00",
  "A La Carte > ORDER OF CHILE RELLENOS (2)": "11.00",
  "A La Carte > ORDER OF TOSTAGUACS (2)": "13.75",
  "A La Carte > ONE CHIMICHANGA WITH CHEESE SAUCE": "9.50",
  "A La Carte > ONE FLAUTA": "4.75",
  "A La Carte > ORDER OF FISH TACOS (3)": "14.50",
  "A La Carte > ONE FISH TACO": "5.50",
  "Side Orders > ORDER OF FRENCH FRIES": "3.25",
  "Side Orders > ORDER OF LETTUCE": "2.00",
  "Side Orders > ORDER OF FLOUR TORTILLAS (2)": "2.00",
  "Side Orders > ORDER OF CORN TORTILLAS (4)": "2.00",
  "Side Orders > SINGLE BURRITO": "7.25",
  "Side Orders > CHALUPA": "7.25",
  "Side Orders > CHILE RELLENO": "7.25",
  "Side Orders > SINGLE ENCHILADA": "4.25",
  "Side Orders > SINGLE TACO": "3.40",
  "Side Orders > SINGLE TAMALE": "4.25",
  "Side Orders > BEEF TOSTADA": "7.25",
  "Side Orders > TOSTAGUAC": "9.00",
  "Side Orders > SLICED AVOCADO": "3.25",
  "El Torero Style Dinners > SPECIAL DINNER": "18.95",
  "El Torero Style Dinners > SPECIAL COMBO": "18.25",
  "El Torero Style Dinners > FLAUTAS": "16.50",
  "El Torero Style Dinners > SINGLE FLAUTA": "8.50",
  "El Torero Style Dinners > CHIMICHANGAS": "17.80",
  "El Torero Style Dinners > SINGLE CHIMICHANGA": "11.00",
  "El Torero Style Dinners > CHILE RANCHERO": "19.25",
  "El Torero Style Dinners > MEXICAN STEW": "19.25",
  "El Torero Style Dinners > CARNE AZADA": "19.25",
  "El Torero Style Dinners > BISTEC RANCHERO": "27.25",
  "El Torero Style Dinners > BISTEC & PEPPERS": "27.25",
  "El Torero Style Dinners > CARNE DE PUERCO": "19.25",
  "El Torero Style Dinners > EL GRANDE (HAND HELD BURRITO)": "12.50",
  "El Torero Style Dinners > PAN SEARED FISH": "18.25",
  "El Torero Style Dinners > PAN SEARED CHICKEN": "18.25",
  "El Torero Style Dinners > NACHOS \"NO CHIPS\"": "14.50",
  "El Torero Style Dinners > NACHOS \"NO CHIPS\" MIXED": "18.75",
  "El Torero Style Dinners > POLLO LOCO": "19.25",
  "El Torero Style Dinners > CHORI POLLO": "19.75",
  "El Torero Style Dinners > POLLO SERRANO": "19.25",
  "El Torero Special Orders > SPECIAL ORDER A": "14.50",
  "El Torero Special Orders > SPECIAL ORDER B": "14.50",
  "El Torero Special Orders > SPECIAL ORDER C": "14.50",
  "El Torero Special Orders > SPECIAL ORDER D": "13.00",
  "El Torero Special Orders > SPECIAL ORDER E": "14.50",
  "El Torero Special Orders > SPECIAL ORDER F": "15.75",
  "El Torero Special Orders > SEPCIAL ORDER ABC": "17.25",
  "El Torero Special Orders > SPECIAL ORDER G": "16.50",
  "Combination Dinners > #1": "14.75",
  "Combination Dinners > #2": "14.75",
  "Combination Dinners > #3": "14.75",
  "Combination Dinners > #4": "14.75",
  "Combination Dinners > #5": "14.75",
  "Combination Dinners > #6": "14.75",
  "Combination Dinners > #7": "14.75",
  "Combination Dinners > #8": "14.75",
  "Combination Dinners > #9": "13.00",
  "Combination Dinners > #10": "14.75",
  "Combination Dinners > #11": "14.75",
  "Combination Dinners > #12": "14.75",
  "Combination Dinners > #13": "14.75",
  "Combination Dinners > #14": "14.75",
  "Combination Dinners > #15": "14.75",
  "Combination Dinners > #16": "14.75",
  "Combination Dinners > #17": "15.40",
  "Combination Dinners > #18": "15.40",
  "Combination Dinners > #19": "15.40",
  "Combination Dinners > #20": "15.40",
  "Combination Dinners > #21": "15.40",
  "Combination Dinners > #22": "15.40",
  "Combination Dinners > #23": "15.40",
  "Combination Dinners > #24": "15.40",
  "Combination Dinners > #25": "15.40",
  "Combination Dinners > #26": "15.40",
  "Combination Dinners > #27": "15.40",
  "Combination Dinners > #28": "15.40",
  "Combination Dinners > #29": "15.40",
  "Combination Dinners > #30": "16.75",
  "Combination Dinners > #31": "15.65",
  "Combination Dinners > #32": "15.65",
  "Combination Dinners > #33": "15.65",
  "Combination Dinners > #34": "15.65",
  "Combination Dinners > #35": "15.65",
  "Combination Dinners > #36": "15.65",
  "Combination Dinners > #37": "15.65",
  "Combination Dinners > #38": "16.75",
  "Combination Dinners > #39": "15.65",
  "Combination Dinners > #40": "15.65",
  "Combination Dinners > #41": "17.75",
  "Combination Dinners > #42": "15.65",
  "Combination Dinners > #43": "15.65",
  "Combination Dinners > #44": "15.65",
  "Combination Dinners > #45": "15.65",
  "Combination Dinners > #46": "15.65",
  "Combination Dinners > #47": "15.65",
  "Combination Dinners > #48": "15.65",
  "Child's Plate > #1": "6.50",
  "Child's Plate > #2": "6.50",
  "Child's Plate > #3": "6.50",
  "Child's Plate > #4": "6.50",
  "Child's Plate > #5": "6.50",
  "Child's Plate > #6": "6.50",
  "Child's Plate > #7": "6.50",
  "Child's Plate > #8": "6.50",
  "Dessert > SOAPAPILLA": "3.50",
  "Dessert > SOAPAPILLA A LA MODE": "5.25",
  "Dessert > FRIED ICE CREAM": "5.25",
  "Dessert > FLAN": "5.25",
  "Dessert > SCOOP OF ICE CREAM": "3.00",
  "Mexican Beer > MEXICAN BEER": "6.00",
  "Mexican Beer > DOMESTIC BEER": "5.75",
  "Draft Beer > PITCHER (60oz,)": "13.75",
  "Draft Beer > HALF PITCHER (32oz.)": "8.00",
  "Draft Beer > JUMBO MUG (32oz.)": "8.00",
  "Draft Beer > GLASS (12oz.)": "4.50",
  "Mixed Drinks > FROZEN MARGARITA (16oz.)": "9.50",
  "Mixed Drinks > PITCHER FROZEN MARGARITA (60oz.)": "27.50",
  "Mixed Drinks > HALF PITCHER FROZEN MARGARITA (32oz.)": "16.25",
  "Mixed Drinks > CHIQUITA MARGARITA": "6.25",
  "Mixed Drinks > GOLD MARGARITA (16oz.)": "11.00",
  "Mixed Drinks > PITCHER GOLD MARGARITA (60oz.)": "29.50",
  "Mixed Drinks > HALF PITCHER GOLD MARGARITA (32oz.)": "17.00",
  "Mixed Drinks > TEXAS MARGARITA (16oz.)": "13.25",
  "Mixed Drinks > PITCHER TEXAS MARGARITA (60oz.)": "36.75",
  "Mixed Drinks > HALF PITCHER TEXAS MARGARITA (32oz.)": "21.00",
  "Mixed Drinks > SMALL TEXAS MARGARITA": "9.75",
  "Mixed Drinks > JOSE CUERVO TEQUILA SHOTS (1oz.)": "7.00",
  "Wines > WHITE ZINFANDEL, CHARDONNAY": "6.00",
  "Wines > HOMEMADE SANGRIA (16oz.)": "7.75",
  "Wines > PITCHER SANGRIA (60oz.)": "21.25",
  "Wines > HALF PITCHER SANGRIA (32oz.)": "13.25",
  "Soft Drinks > SOFT DRINKS": "3.25",
  "Soft Drinks > MILK, COFFEE, GREEN TEA": "3.25",
  "Soft Drinks > SHIRLEY TEMPLE": "3.25",
  "Soft Drinks > MILKSHAKE": "3.85",
  "Soft Drinks > AGUA DE HORCHATA": "3.35"
};
