/*
 * EL TORERO MENU PRICES
 *
 * Edit prices ONLY in this file.
 * Format: "Section > ITEM NAME": "9.99"
 * For duplicate items in one section, use an array in display order.
 */
window.MENU_PRICE_OVERRIDES = {
  "Appetizers > CHEESE DIP": "8.50",
  "Appetizers > GUACAMOLE DIP": "8.50",
  "Appetizers > QUESADILLA": "4.60",
  "Appetizers > SPECIAL QUESADILLA": "6.50",
  "Appetizers > STUFFED QUESADILLA": "6.75",
  "Appetizers > SPECIAL STUFFED QUESADILLA": "8.25",
  "Appetizers > QUESADILLA PLATTER": "12.50",
  "Appetizers > CHEESE NACHOS": "7.50",
  "Appetizers > HALF-ORDER CHEESE NACHOS": "5.75",
  "Appetizers > NACHOS": ["8.50", "9.25"],
  "Appetizers > HALF-ORDER NACHOS": ["6.50", "7.00"],
  "Appetizers > SPECIAL NACHOS": "11.00",
  "Appetizers > HALF-ORDER SPECIAL NACHOS": "7.75",
  "Soups & Salads > GUACAMOLE SALAD": "5.50",
  "Soups & Salads > TACO SALAD": "8.75",
  "Soups & Salads > SPECIAL TACO SALAD": "9.75",
  "Soups & Salads > TORTILLA SOUP WITH CHICKEN OR SHRIMP": "8.25",
  "Soups & Salads > POZOLE SOUP": "8.25",
  "Lunch > SPEEDY GONZALEZ": "7.85",
  "Lunch > SPECIAL LUNCH #1": "9.70",
  "Lunch > SPECIAL LUNCH #2": "8.70",
  "Lunch > SPECIAL LUNCH #3": "8.70",
  "Lunch > SPECIAL LUNCH #4": "7.85",
  "Lunch > SPECIAL LUNCH #5": "8.70",
  "Lunch > SPECIAL LUNCH #6": "8.70",
  "Lunch > SPECIAL LUNCH #7": "9.70",
  "Lunch > SPECIAL LUNCH #8": "8.70",
  "Lunch > SPECIAL LUNCH #9": "7.85",
  "Lunch > SPECIAL LUNCH #10": "8.70",
  "Lunch > SPECIAL LUNCH #11": "7.60",
  "Lunch > SPECIAL LUNCH #12": "7.85",
  "Lunch > SPECIAL LUNCH #13": "7.85",
  "Lunch > SPECIAL LUNCH #14": "8.70",
  "Lunch > SPECIAL LUNCH #15": "8.70",
  "A La Carte > ORDER OF BEANS": "2.50",
  "A La Carte > ORDER OF RICE": "2.50",
  "A La Carte > ORDER OF TACOS (3)": "9.00",
  "A La Carte > ORDER OF TAMALES (3)": "9.00",
  "A La Carte > ORDER OF ENCHILADAS (3)": "9.00",
  "A La Carte > ORDER OF BEEF TOSTADAS (2)": "9.50",
  "A La Carte > ORDER OF BURRITOS (2)": "9.50",
  "A La Carte > ORDER OF CHALUPAS (2)": "9.50",
  "A La Carte > ORDER OF CHILE RELLENOS (2)": "9.50",
  "A La Carte > ORDER OF TOSTAGUACS (2)": "10.50",
  "A La Carte > ONE CHIMICHANGA WITH CHEESE SAUCE": "7.75",
  "A La Carte > ONE FLAUTA": "4.75",
  "A La Carte > ORDER OF FISH TACOS (3)": "11.50",
  "A La Carte > ONE FISH TACO": "5.00",
  "Side Orders > ORDER OF FRENCH FRIES": "2.00",
  "Side Orders > ORDER OF LETTUCE": "1.25",
  "Side Orders > ORDER OF FLOUR TORTILLAS (2)": "1.50",
  "Side Orders > ORDER OF CORN TORTILLAS (4)": "1.50",
  "Side Orders > SINGLE BURRITO": "6.50",
  "Side Orders > CHALUPA": "6.50",
  "Side Orders > CHILE RELLENO": "6.50",
  "Side Orders > SINGLE ENCHILADA": "3.75",
  "Side Orders > SINGLE TACO": "3.15",
  "Side Orders > SINGLE TAMALE": "3.75",
  "Side Orders > BEEF TOSTADA": "6.50",
  "Side Orders > TOSTAGUAC": "7.25",
  "Side Orders > SLICED AVOCADO": "2.50",
  "El Torero Style Dinners > SPECIAL DINNER": "18.95",
  "El Torero Style Dinners > SPECIAL COMBO": "16.25",
  "El Torero Style Dinners > FLAUTAS": "14.55",
  "El Torero Style Dinners > SINGLE FLAUTA": "7.85",
  "El Torero Style Dinners > CHIMICHANGAS": "15.80",
  "El Torero Style Dinners > SINGLE CHIMICHANGA": "9.50",
  "El Torero Style Dinners > CHILE RANCHERO": "17.25",
  "El Torero Style Dinners > MEXICAN STEW": "17.25",
  "El Torero Style Dinners > CARNE AZADA": "17.25",
  "El Torero Style Dinners > BISTEC RANCHERO": "23.25",
  "El Torero Style Dinners > BISTEC & PEPPERS": "23.25",
  "El Torero Style Dinners > CARNE DE PUERCO": "16.45",
  "El Torero Style Dinners > EL GRANDE (HAND HELD BURRITO)": "10.50",
  "El Torero Style Dinners > PAN SEARED FISH": "15.25",
  "El Torero Style Dinners > PAN SEARED CHICKEN": "15.25",
  "El Torero Style Dinners > NACHOS \"NO CHIPS\"": "12.50",
  "El Torero Style Dinners > NACHOS \"NO CHIPS\" MIXED": "15.25",
  "El Torero Style Dinners > POLLO LOCO": "16.25",
  "El Torero Style Dinners > CHORI POLLO": "16.75",
  "El Torero Style Dinners > POLLO SERRANO": "16.25",
  "El Torero Special Orders > SPECIAL ORDER A": "12.75",
  "El Torero Special Orders > SPECIAL ORDER B": "13.00",
  "El Torero Special Orders > SPECIAL ORDER C": "13.00",
  "El Torero Special Orders > SPECIAL ORDER D": "13.00",
  "El Torero Special Orders > SPECIAL ORDER E": "13.00",
  "El Torero Special Orders > SPECIAL ORDER F": "13.25",
  "El Torero Special Orders > SEPCIAL ORDER ABC": "13.85",
  "El Torero Special Orders > SPECIAL ORDER G": "14.00",
  "Combination Dinners > #1": "13.25",
  "Combination Dinners > #2": "13.25",
  "Combination Dinners > #3": "13.25",
  "Combination Dinners > #4": "13.25",
  "Combination Dinners > #5": "13.25",
  "Combination Dinners > #6": "13.25",
  "Combination Dinners > #7": "13.25",
  "Combination Dinners > #8": "13.25",
  "Combination Dinners > #9": "12.00",
  "Combination Dinners > #10": "13.00",
  "Combination Dinners > #11": "13.25",
  "Combination Dinners > #12": "13.25",
  "Combination Dinners > #13": "13.25",
  "Combination Dinners > #14": "13.25",
  "Combination Dinners > #15": "13.25",
  "Combination Dinners > #16": "13.25",
  "Combination Dinners > #17": "13.90",
  "Combination Dinners > #18": "13.90",
  "Combination Dinners > #19": "13.90",
  "Combination Dinners > #20": "13.90",
  "Combination Dinners > #21": "13.90",
  "Combination Dinners > #22": "13.90",
  "Combination Dinners > #23": "13.90",
  "Combination Dinners > #24": "13.90",
  "Combination Dinners > #25": "13.90",
  "Combination Dinners > #26": "13.90",
  "Combination Dinners > #27": "13.90",
  "Combination Dinners > #28": "13.90",
  "Combination Dinners > #29": "13.90",
  "Combination Dinners > #30": "14.15",
  "Combination Dinners > #31": "14.15",
  "Combination Dinners > #32": "14.15",
  "Combination Dinners > #33": "14.15",
  "Combination Dinners > #34": "14.15",
  "Combination Dinners > #35": "14.15",
  "Combination Dinners > #36": "14.15",
  "Combination Dinners > #37": "14.15",
  "Combination Dinners > #38": "15.25",
  "Combination Dinners > #39": "14.15",
  "Combination Dinners > #40": "14.15",
  "Combination Dinners > #41": "16.00",
  "Combination Dinners > #42": "14.15",
  "Combination Dinners > #43": "14.15",
  "Combination Dinners > #44": "14.15",
  "Combination Dinners > #45": "14.15",
  "Combination Dinners > #46": "14.15",
  "Combination Dinners > #47": "14.15",
  "Combination Dinners > #48": "14.15",
  "Child's Plate > #1": "6.00",
  "Child's Plate > #2": "6.00",
  "Child's Plate > #3": "6.00",
  "Child's Plate > #4": "6.00",
  "Child's Plate > #5": "6.00",
  "Child's Plate > #6": "6.00",
  "Child's Plate > #7": "6.00",
  "Child's Plate > #8": "6.00",
  "Dessert > SOAPAPILLA": "2.90",
  "Dessert > SOAPAPILLA A LA MODE": "4.25",
  "Dessert > FRIED ICE CREAM": "4.25",
  "Dessert > FLAN": "4.25",
  "Dessert > SCOOP OF ICE CREAM": "2.25",
  "Mexican Beer > MEXICAN BEER": "5.50",
  "Mexican Beer > DOMESTIC BEER": "5.00",
  "Draft Beer > PITCHER (60oz,)": "12.50",
  "Draft Beer > HALF PITCHER (32oz.)": "7.00",
  "Draft Beer > JUMBO MUG (32oz.)": "7.00",
  "Draft Beer > GLASS (12oz.)": "3.75",
  "Mixed Drinks > FROZEN MARGARITA (16oz.)": "8.50",
  "Mixed Drinks > PITCHER FROZEN MARGARITA (60oz.)": "25.50",
  "Mixed Drinks > HALF PITCHER FROZEN MARGARITA (32oz.)": "14.25",
  "Mixed Drinks > CHIQUITA MARGARITA": "5.50",
  "Mixed Drinks > GOLD MARGARITA (16oz.)": "9.00",
  "Mixed Drinks > PITCHER GOLD MARGARITA (60oz.)": "27.00",
  "Mixed Drinks > HALF PITCHER GOLD MARGARITA (32oz.)": "15.00",
  "Mixed Drinks > TEXAS MARGARITA (16oz.)": "11.75",
  "Mixed Drinks > PITCHER TEXAS MARGARITA (60oz.)": "33.25",
  "Mixed Drinks > HALF PITCHER TEXAS MARGARITA (32oz.)": "18.00",
  "Mixed Drinks > SMALL TEXAS MARGARITA": "7.75",
  "Mixed Drinks > JOSE CUERVO TEQUILA SHOTS (1oz.)": "6.25",
  "Wines > WHITE ZINFANDEL, CHARDONNAY": "5.00",
  "Wines > HOMEMADE SANGRIA (16oz.)": "6.25",
  "Wines > PITCHER SANGRIA (60oz.)": "17.50",
  "Wines > HALF PITCHER SANGRIA (32oz.)": "10.00",
  "Soft Drinks > SOFT DRINKS": "2.95",
  "Soft Drinks > MILK, COFFEE, GREEN TEA": "2.95",
  "Soft Drinks > SHIRLEY TEMPLE": "2.95",
  "Soft Drinks > MILKSHAKE": "3.85",
  "Soft Drinks > AGUA DE HORCHATA": "2.95"
};
